// ============================================================
// SITE CONFIGURATION
// ============================================================

const SITE_CONFIG = {
  photographerName: 'Raveen Fernando',
  // ── Site-wide preview password (SHA-256 hash) ──
  // To change: python3 -c "import hashlib; print(hashlib.sha256(b'yourpassword').hexdigest())"
  sitePasswordHash: '36e11b86750178bc2d659d7779dbfdf28cee8c60a6a804e47d3ef1ae85f4a70c',
  // Admin panel password hash — protect /admin.html
  // Password stored separately; to change: python3 -c "import hashlib; print(hashlib.sha256(b'newpassword').hexdigest())"
  adminPasswordHash: '5be8a85ba815c0473d9a609eb5a6d7dbeaf1e32045456bda1ea209ebecd211d8',
  tagline: 'Capturing light, emotion, and the quiet beauty of the world.',
  // ── Hero background (home page) — served from /images/ for same-origin preload ──
  heroImage: '/images/hero.jpg',
  heroPosition: '50% 50%',
  heroPositionMobile: '50% 40%',

  // ── R2: Upload your about/profile photo and set the URL below ──
  aboutPhoto: 'https://picsum.photos/seed/about-portrait/800/1000',
  aboutBio: `I'm a photographer based in Detroit, Michigan.`,
  email: 'raveen.l.fernando@gmail.com',
};

// ============================================================
// CLOUDFLARE R2 CONFIGURATION
// ── Replace R2_BASE_URL with your R2 public bucket URL ──
// Format 1 (R2 public URL):   https://pub-XXXX.r2.dev
// Format 2 (custom domain):   https://photos.yourdomain.com
//
// ⚠️  Ensure your R2 bucket has CORS configured to allow GET
//     requests from your domain (needed for the ZIP download).
// ============================================================
const R2_BASE_URL = 'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev';

// ============================================================
// ALBUM CONFIGURATION
//
// Each album object:
//   id          – unique slug used in URLs (?id=landscapes)
//   title       – display name
//   description – short caption shown on gallery card (hover)
//   location    – place name for dateline (e.g. "Venice")
//   date        – date string for dateline (e.g. "May 2026")
//   dateline    – optional override; default built from location · date · N frames
//   protected   – true = password required
//   passwordHash– SHA-256 hash of the album password (protected only)
//                 Generate: open browser console and run:
//                   hashPassword('your-password').then(h => console.log(h))
//                 (hashPassword is defined in js/main.js)
//   coverImage  – path relative to R2_BASE_URL, or full URL for placeholders
//   photos      – array of digital photo URLs inside the album
//   digitalLabel– optional heading above the digital grid (e.g. "Fujifilm X-T5")
//   digitalNavLabel – optional short jump-nav label for digital (default: "Digital")
//   filmSections[].navLabel – optional short jump-nav label (default: "Film Roll N")
//   filmPhotos  – optional film frames appended after photos (separate grid section)
//   filmLabel   – optional heading for the film section (default: "On film")
//   filmSections– optional array of { label, photos } for multiple film blocks
// ============================================================
const ALBUMS = [

  // ── HIDDEN CLIENT ALBUMS ──────────────────────────────────
  {
    id: 'joel-bday-2025',
    title: 'Joel Birthday 2025',
    description: 'Joel\'s birthday — October 2025.',
    location: 'Detroit',
    date: 'October 2025',
    hidden: true,
    protected: true,
    passwordHash: '2d2b01d274945379effbc06b47517c211bee6f4f57ea4be7c15e76d334386862',
    coverImage: `${R2_BASE_URL}/Joel-Bday-2025/DSCF6858.JPG`,
    photos: [
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6858.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6866.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6867.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6869.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6876.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6885.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6887.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6891.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6892.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6895.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6908.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6912.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6915.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6916.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6917.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6922.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6924.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6925.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6929.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6932.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6933.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6937.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6938.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6939.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6941.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6943.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6949.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6952.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6953.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6957.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6958.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6959.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6970.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6971.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6974.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6975.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6977.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6978.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6982.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6983.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6984.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6990.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6997.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF6999.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7005.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7006.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7008.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7010.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7011.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7013.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7014.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7016.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7018.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7021.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7022.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7024.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7025.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7026.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7030.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7031.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7034.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7035.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7040.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7041.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7042.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7043.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7045.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7047.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7053.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7077.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7087.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7088.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7093.JPG`,
      `${R2_BASE_URL}/Joel-Bday-2025/DSCF7095.JPG`,
    ],
  },

  // ── CALIFORNIA 2025 ───────────────────────────────────────
  {
    id: 'california',
    title: 'California 2025',
    description: 'Santa Cruz, Big Sur, and Yosemite.',
    location: 'California',
    date: 'July 2025',
    type: 'group',
    protected: false,
    subAlbums: ['california-santa-cruz', 'california-yosemite'],
    coverImage: `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-188.jpg`,
  },

  {
    id: 'california-santa-cruz',
    title: 'Santa Cruz & Big Sur',
    parentId: 'california',
    location: 'Santa Cruz & Big Sur',
    date: 'July 2025',
    protected: false,
    coverImage: `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-141.jpg`,
    photos: [
`${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-009.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-011.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-026.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-041.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-042.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-050.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-060.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-061.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-068.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-074.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-075.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-078.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-081.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-084.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-088.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-093.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-098.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-099.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-100.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-104.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-106.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-112.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-118.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-120.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-124.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-126.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-139.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-141.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-164.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-169.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-174.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-176.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-179.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-188.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-200.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-203.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-205.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-208.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-213.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-216.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-219.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-225.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-227.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-231.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-238.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-249.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-276.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-281.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-282.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-297.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-309.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-314.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-324.jpg`,
    ],
  },

  {
    id: 'california-yosemite',
    title: 'Yosemite',
    parentId: 'california',
    location: 'Yosemite',
    date: 'July 2025',
    protected: false,
    coverImage: `${R2_BASE_URL}/California/Yosemite/California-404.jpg`,
    photos: [
      `${R2_BASE_URL}/California/Yosemite/California-339.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-344.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-346.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-349.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-356.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-362.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-366.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-381.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-383.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-385.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-387.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-393.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-395.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-404.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-407.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-408.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-409.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-412.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-413.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-418.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-419.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-426.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-427.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-430.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-431.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-432.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-442.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-443.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-444.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-450.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-453.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-455.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-456.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-459.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-465.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-469.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-472.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-473.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-488.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-496.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-515.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-517.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-538.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-540.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-547.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-550.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-551.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-555.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-567.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-568.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-573.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-575.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-576.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-583.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-587.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-589.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-593.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-594.jpg`,
    ],
  },

  {
    id: 'london-2025',
    title: 'London 2025',
    location: 'London',
    date: 'September 2025',
    description: 'Photos from this trip are still being edited.',
    protected: false,
    coverImage: '/images/placeholder-album.svg',
    photos: [],
  },

  // ── GROUP ALBUMS ──────────────────────────────────────────
  // type: 'group' albums show a sub-album index page instead of photos.
  // Add photo URLs to each sub-album's photos array once uploaded to R2.
  {
    id: 'italy-2026',
    title: 'Italy 2026',
    description: 'Venice, Florence, Rome, and more.',
    location: 'Italy',
    date: 'May–June 2026',
    type: 'group',
    protected: false,
    curatePasswordHash: '0705fe0ca5eef5e42cbee84e7721b22565f303248adbbc21342bfd9d901db572',
    subAlbums: ['italy-venice', 'italy-pisa', 'italy-florence', 'italy-assisi', 'italy-rome'],
    coverImage: `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_097-Edit.jpg`,
    coverPosition: '50% 22%',
  },

  {
    id: 'italy-venice',
    slug: 'venice',
    title: 'Venice',
    parentId: 'italy-2026',
    description: 'Venice, 30–31 May 2026.',
    location: 'Venice',
    date: 'May 2026',
    protected: false,
    digitalLabel: 'Fujifilm X-T5',
    coverImage: `${R2_BASE_URL}/Italy/Venice/Digital/venice_284.jpg`,
    photos: [
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_042.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_069.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_087.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_097.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_098.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_104.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_108.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_111.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_113.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_123.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_125.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_134.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_140.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_144.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_148.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_152.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_155.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_160.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_162.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_165.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_168.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_169.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_170.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_172.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_174.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_178.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_184.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_195.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_209.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_222.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_226.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_227.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_228.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_232.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_235.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_236.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_263.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_264.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_269.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_274.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_278.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_280.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_284.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_287.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_289.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_303.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_311.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_315.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_328.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_329.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_344.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_346.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_352.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_358.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_361.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_362.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_364.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_371.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_372.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_376.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_377.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_381.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_392.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_417.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_418.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_420.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_422.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_425.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_428.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_432.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_438.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_441.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_446.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_451.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_453.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_457.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_459.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_462.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_464.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_468.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_473.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_482.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_485.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_489.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_501.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_520.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_536.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_567.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_577.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_589.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_608.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_619.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_620.jpg`,
      `${R2_BASE_URL}/Italy/Venice/Digital/venice_622.jpg`,
    ],
    filmSections: [
      {
        label: 'Kodak Ultramax 400',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_01.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_02.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_03.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_04.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_05.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_06.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_07.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_08.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_09.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_10.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_11.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_12.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_13.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_14.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_15.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_16.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_17.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_18.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_19.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_20.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_21.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_22.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_23.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_24.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_25.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_26.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_27.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_28.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_29.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_30.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_31.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_32.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_33.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_34.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_35.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_36.jpg`,
          `${R2_BASE_URL}/Italy/Film/Ultramax/ultramax_37.jpg`,
        ],
      },
      {
        label: 'Ilford FP4 Plus 125',
        photos: [
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E001.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E002.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E003.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E004.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E005.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E006.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E007.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E008.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E009.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E010.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E011.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E012.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E013.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E014.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E015.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E016.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E017.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E018.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E019.jpg`,
        ],
      },
      {
        label: 'Half Frame Kodak Ultramax 400',
        navLabel: 'Athena\'s Film Roll 1',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_005.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_007.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_008.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_009.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_010.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_013.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_015.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_016.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_017.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_019.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_020.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_021.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_022.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_023.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_024.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_025.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_026.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_028.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_029.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_030.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_032.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_033.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_034.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_037.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_038.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_039.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_040.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_041.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_043.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_044.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_045.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_046.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_048.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_049.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_052.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_053.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_055.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_057.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_058.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_059.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_060.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_062.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_066.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_068.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_069.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_073.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-1/athena_ultramax1_074.jpg`,
        ],
      },

    ],
  },

  {
    id: 'italy-florence',
    slug: 'florence',
    title: 'Florence',
    parentId: 'italy-2026',
    description: 'Florence, 1–2 June 2026.',
    location: 'Florence',
    date: 'June 2026',
    protected: false,
    digitalLabel: 'Fujifilm X-T5',
    coverImage: `${R2_BASE_URL}/Italy/Florence/Digital/florence_400.jpg`,
    coverPosition: '50% 35%',
    photos: [
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_006.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_016.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_017.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_022.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_047.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_060.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_081.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_085.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_092.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_106.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_108.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_127.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_164.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_180.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_182.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_191.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_199.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_201.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_207.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_210.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_213.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_217.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_219.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_237.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_240.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_244.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_246.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_251.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_253.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_255.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_288.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_291.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_299.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_307.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_312.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_315.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_319.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_321.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_322.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_327.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_335.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_338.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_348.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_349.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_359.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_364.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_374.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_380.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_383.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_396.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_400.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_406.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_411.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_423.jpg`,
      `${R2_BASE_URL}/Italy/Florence/Digital/florence_425.jpg`,
    ],
    filmSections: [
      {
        label: 'Ilford FP4 Plus 125',
        navLabel: 'Film Roll 2',
        photos: [
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E029.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E030.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E031.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E032.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E033.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E034.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E035.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E036.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E037.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E038.jpg`,
        ],
      },
      {
        label: 'Kodak T-Max 400',
        navLabel: 'Film Roll 3',
        photos: [
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E001.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E002.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E003.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E004.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E005.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E006.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E007.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E008.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E009.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E010.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E011.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E012.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E013.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E014.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E015.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E016.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E017.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E018.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E019.jpg`,
        ],
      },
      {
        label: 'Half Frame Kodak Ultramax 400',
        navLabel: 'Athena\'s Film Roll 2',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_015.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_017.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_019.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_020.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_021.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_022.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_023.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_025.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_026.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_028.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_030.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_031.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_033.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_034.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_036.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_037.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_039.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_041.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_042.jpg`,
        ],
      },

    ],
  },

  {
    id: 'italy-pisa',
    slug: 'pisa',
    title: 'Pisa',
    parentId: 'italy-2026',
    description: 'Pisa, 1 June 2026.',
    location: 'Pisa',
    date: 'June 2026',
    protected: false,
    digitalLabel: 'Fujifilm X-T5',
    coverImage: `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_097-Edit.jpg`,
    coverPosition: '50% 22%',
    photos: [
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_005.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_007.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_016.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_024.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_035.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_042.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_044.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_045.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_055.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_059.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_061.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_062.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_074.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_083.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_091.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_093.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_095.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_097-Edit.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_109.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_134.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_136.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_137.jpg`,
      `${R2_BASE_URL}/Italy/Pisa/Digital/pisa_162.jpg`,
    ],
    filmSections: [
      {
        label: 'Ilford FP4 Plus 125',
        navLabel: 'Film Roll 2',
        photos: [
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E020.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E021.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E022.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E023.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E024.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E025.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E026.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E027.jpg`,
          `${R2_BASE_URL}/Italy/Film/FP4/Fernando000799-R1-E028.jpg`,
        ],
      },
      {
        label: 'Half Frame Kodak Ultramax 400',
        navLabel: 'Athena\'s Film Roll 2',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_004.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_005.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_006.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_008.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_010.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_013.jpg`,
        ],
      },

    ],
  },

  {
    id: 'italy-assisi',
    slug: 'assisi',
    title: 'Assisi',
    parentId: 'italy-2026',
    description: 'Assisi, 3 June 2026.',
    location: 'Assisi',
    date: 'June 2026',
    protected: false,
    digitalLabel: 'Fujifilm X-T5',
    coverImage: `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_034.jpg`,
    photos: [
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_004.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_011.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_014.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_024.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_025.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_031.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_034.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_036.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_039.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_050.jpg`,
      `${R2_BASE_URL}/Italy/Assisi/Digital/assisi_055.jpg`,
    ],
    filmSections: [
      {
        label: 'Kodak T-Max 400',
        navLabel: 'Film Roll 3',
        photos: [
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E020.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E021.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E022.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E023.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E024.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E025.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E026.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E027.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E028.jpg`,
        ],
      },
      {
        label: 'Half Frame Kodak Ultramax 400',
        navLabel: 'Athena\'s Film Roll 2',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_043.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_046.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_052.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_054.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_055.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_056.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_057.jpg`,
        ],
      },

    ],
  },

  {
    id: 'italy-rome',
    slug: 'rome',
    title: 'Rome',
    parentId: 'italy-2026',
    location: 'Rome',
    date: 'June 2026',
    protected: false,
    digitalLabel: 'Fujifilm X-T5',
    coverImage: `${R2_BASE_URL}/Italy/Rome/Digital/rome_495.jpg`,
    photos: [
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_002.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_029.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_036.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_053.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_061.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_063.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_103.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_132.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_136.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_144.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_150.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_151.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_163.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_176.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_177.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_182.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_195.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_202.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_203.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_208.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_214.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_226.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_233.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_247.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_266.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_268.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_279.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_328.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_339.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_342.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_353.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_359.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_362.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_370.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_376.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_377.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_386.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_388.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_390.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_446.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_468.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_487.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_495.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_531.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_533.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_542.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_582.jpg`,
      `${R2_BASE_URL}/Italy/Rome/Digital/rome_586.jpg`,
    ],
    filmSections: [
      {
        label: 'Kodak T-Max 400',
        navLabel: 'Film Roll 3',
        photos: [
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E029.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E030.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E031.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E032.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E033.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E034.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E035.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E036.jpg`,
          `${R2_BASE_URL}/Italy/Film/TMAX/Fernando000800-R1-E037.jpg`,
        ],
      },
      {
        label: 'Kodak Portra 160',
        navLabel: 'Film Roll 4',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_01.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_02.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_03.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_04.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_05.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_06.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_07.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_08.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_09.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_10.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_11.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_12.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_13.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_14.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_15.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_16.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_17.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_18.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_19.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_20.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_21.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_22.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_23.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_24.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_25.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_26.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_27.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_28.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_29.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_30.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_31.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_32.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_33.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_34.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_35.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_36.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_37.jpg`,
          `${R2_BASE_URL}/Italy/Film/Portra/Raveen_portra_38.jpg`,
        ],
      },
      {
        label: 'Half Frame Kodak Ultramax 400',
        navLabel: 'Athena\'s Film Roll 2',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_058.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_062.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_064.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_067.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_068.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_069.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_075.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ultramax-2/athena_ultramax2_078.jpg`,
        ],
      },
      {
        label: 'Half Frame Kodak Ektar 100',
        navLabel: 'Athena\'s Film Roll 3',
        photos: [
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_005.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_009.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_010.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_013.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_017.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_020.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_023.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_024.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_025.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_027.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_034.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_035.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_037.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_038.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_039.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_040.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_044.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_048.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_050.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_053.jpg`,
          `${R2_BASE_URL}/Italy/Film/Athena-Ektar100/athena_ektar100_055.jpg`,
        ],
      },

    ],
  },

];
