// ============================================================
// california-2025.js
// ============================================================
// This file is loaded by all pages via albums.js.
// California 2025 — public friends-visible trip.
// ============================================================

// eslint-disable-next-line no-unused-vars
const ALBUMS_CALIFORNIA = [
  // ── CALIFORNIA 2025 ───────────────────────────────────────
  {
    id: 'california',
    title: 'California 2025',
    description: 'Santa Cruz, Big Sur, and Yosemite.',
    location: 'California',
    date: 'July 2025',
    type: 'group',
    audience: 'friends',
    protected: false,
    subAlbums: ['california-santa-cruz', 'california-yosemite'],
    coverImage: `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-188.jpg`,
  },

  {
    id: 'california-santa-cruz',
    title: 'Santa Cruz & Big Sur',
    parentId: 'california',
    location: 'Santa Cruz & Big Sur',
    date: 'July 2025',
    audience: 'friends',
    protected: false,
    coverImage: `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-141.jpg`,
    photos: [
`${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-009.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-011.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-026.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-041.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-042.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-050.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-060.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-061.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-068.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-074.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-075.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-078.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-081.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-084.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-088.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-093.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-098.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-099.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-100.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-104.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-106.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-112.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-118.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-120.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-124.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-126.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-139.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-141.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-164.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-169.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-174.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-176.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-179.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-188.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-200.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-203.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-205.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-208.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-213.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-216.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-219.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-225.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-227.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-231.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-238.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-249.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-276.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-281.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-282.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-297.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-309.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-314.jpg`,
      `${R2_BASE_URL}/California/Santa-Cruz-Big-Sur/California-324.jpg`,
    ],
    curated: [
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-026.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-060.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-061.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-078.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-093.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-106.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-118.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-139.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-141.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-174.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-176.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-188.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-200.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-213.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-225.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-238.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-249.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-297.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Santa-Cruz-Big-Sur/California-324.jpg',
    ],
  },

  {
    id: 'california-yosemite',
    title: 'Yosemite',
    parentId: 'california',
    location: 'Yosemite',
    date: 'July 2025',
    audience: 'friends',
    protected: false,
    coverImage: `${R2_BASE_URL}/California/Yosemite/California-404.jpg`,
    photos: [
      `${R2_BASE_URL}/California/Yosemite/California-339.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-344.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-346.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-349.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-356.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-362.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-366.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-381.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-383.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-385.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-387.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-393.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-395.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-404.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-407.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-408.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-409.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-412.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-413.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-418.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-419.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-426.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-427.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-430.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-431.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-432.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-442.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-443.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-444.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-450.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-453.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-455.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-456.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-459.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-465.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-469.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-472.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-473.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-488.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-496.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-515.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-517.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-538.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-540.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-547.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-550.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-551.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-555.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-567.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-568.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-573.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-575.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-576.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-583.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-587.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-589.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-593.jpg`,
      `${R2_BASE_URL}/California/Yosemite/California-594.jpg`,
    ],
    curated: [
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-346.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-362.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-381.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-404.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-407.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-412.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-419.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-426.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-453.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-455.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-488.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-517.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-540.jpg',
      'https://pub-d6285edfbb3747a9bbfc77b32aac2baa.r2.dev/California/Yosemite/California-547.jpg',
    ],
  },

  {
    id: 'london-2025',
    title: 'London 2025',
    location: 'London',
    date: 'September 2025',
    description: 'Photos from this trip are still being edited.',
    hidden: true,
    audience: 'public',
    protected: false,
    coverImage: '/images/placeholder-album.svg',
    photos: [],
  },

];
